### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by valdisiljuconoks** [episerver/DeveloperTools#1]
None of links from menu are handled by plugin. Everything results in 404

**Comment by valdisiljuconoks** [comment]
This was false alarm. Sorry for any inconveniences.

**Comment by ksjoberg** [comment]
Thanks for getting back and closing it.  I guess there was something you did that fixed the problem?  Can you share it?

**Comment by valdisiljuconoks** [comment]
Problem was that we migrated solution, moved it around here and there and .dll was still sitting in modulesbin but EPiServer.DeveloperTools was gone from AppData/Modules - therefore menu was still generated by dll from modulesbin with incorrect links.
