### ISSUE TITLE
Undocumented dependency to log4net

### ISSUE THREAD

**Issue by defsteph** [episerver/DeveloperTools#20]
There is no dependency to the log4net nuget package, but if you run this in a site that doesn't have it installed, it crashes.

**Comment by bjuris** [comment]
Hmm, seems like a bad idea to require log4net for this tool. Maybe we could make the "Log" tool go away if not log4net installed, or make it work with all loggers..

**Comment by valdisiljuconoks** [comment]
Yup, looks like bug

**Comment by valdisiljuconoks** [comment]
Maybe it's worth to add dependency for now, and then refactor it out?

**Comment by valdisiljuconoks** [comment]
@bjuris This can be closed as well.

**Comment by valdisiljuconoks** [comment]
@bjuris close?!
