### ISSUE TITLE
Developer tools is adding partial Clear local object cache plug-in

### ISSUE THREAD

**Issue by joemayberry** [episerver/DeveloperTools#39]
Hi Valdis,

I just noticed that the DeveloperTool NuGet package is trying to add a "Clear Local Object Cache" plug-in, with a link in the Admin -> Tools section, which it should not do. The link throws an exception when you try to run it, because the view isn't set up.

It runs fine when accessing it from the Developer menu.

![ClearLocalObjectCache](https://user-images.githubusercontent.com/47357457/57393352-e6a03880-7190-11e9-8837-3cbb88bf102a.png)

I don't see that in the code to add that in GitHub. Could something be in the NuGet package?

Thanks,
Joe Mayberry

**Comment by valdisiljuconoks** [comment]
hi,

could it be leftover from your previous version of the plugin? did you try on empty alloy?

**Comment by joemayberry** [comment]
Hi,

I did try it on a fresh Alloy site. That’s when I noticed it.

Thanks,

Joe Mayberry

**Comment by valdisiljuconoks** [comment]
yes, found out that I didn't either push 3.4.1 package out or it was not accepted :)
fixing this..

**Comment by valdisiljuconoks** [comment]
package is officially now on feed
