### ISSUE TITLE
Link to analysis of side-effects is broken

### ISSUE THREAD

**Issue by modestotech** [episerver/DeveloperTools#56]
[Känner att jag måste börja rita en bild av nuvarande flöde för att förstå var jag ska in och fixa saker, för just nu är allt rörigt i koden och i mitt huvud](https://github.com/episerver/DeveloperTools#how-risky-it-is-to-install-on-production)

The link https://blog.tech-fellow.net/2019/02/14/how-risky-are-episerver-developertools-on-production-environment/ goes to a generic site.

**Comment by valdisiljuconoks** [comment]
link fixed
