### ISSUE TITLE
EPiServer v10 Support

### ISSUE THREAD

**Issue by valdisiljuconoks** [episerver/DeveloperTools#7]

**Comment by valdisiljuconoks** [comment]
Can you create new release for downloading .nupkg file?

Thx

**Comment by bjuris** [comment]
Will do

**Comment by valdisiljuconoks** [comment]
Any progress? Already announced that tools are available for v10 ;)

**Comment by bjuris** [comment]
Been on vacation, will do it later today :)

**Comment by valdisiljuconoks** [comment]
Oh, sorry! Happy New Year! :)

**Comment by valdisiljuconoks** [comment]
Awesome, thx!
